export const dynamic = "force-dynamic";

import { requireUser } from "@/lib/auth/session";
import { getRecommendationsAction } from "@/lib/agents/actions";
import { Lightbulb, CheckCircle, ChevronRight } from "lucide-react";
import {
  AgentStat, PriorityBadge, ConfidenceRing, AgentSubNav,
} from "@/components/agents/agent-ui";
import { fmtDate } from "@/lib/agents/utils";
import { RecommendationActions } from "@/components/agents/recommendation-actions";

const IMPACT_STYLES: Record<string, string> = {
  Critical: "text-red-400",
  High:     "text-orange-400",
  Medium:   "text-amber-400",
  Low:      "text-blue-400",
};

const EFFORT_STYLES: Record<string, string> = {
  Low:    "text-emerald-400",
  Medium: "text-amber-400",
  High:   "text-red-400",
};

export default async function RecommendationsPage() {
  await requireUser();
  const result = await getRecommendationsAction().catch(() => null);
  const recs = ((result as { data?: unknown[] } | null)?.data ?? []) as Array<{
    id: string; title: string; rationale: string; suggestedActions: string[];
    priority: string; confidence: number; impactLabel: string; effortLabel: string;
    status: string; agentName: string; createdAt: string;
  }>;

  const open     = recs.filter(r => r.status === "open");
  const urgent   = recs.filter(r => r.priority === "urgent");
  const accepted = recs.filter(r => r.status === "accepted");

  return (
    <div className="space-y-6 p-6">
      <AgentSubNav />

      {/* Header */}
      <div className="pt-2">
        <h1 className="font-[family-name:var(--font-display)] text-2xl font-bold">Agent Recommendations™</h1>
        <p className="mt-1 text-sm text-[var(--color-ink-dim)]">Prioritized governance actions generated by your AI agents.</p>
      </div>

      {/* KPIs */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <AgentStat label="Total"    value={recs.length}    accent="neutral" />
        <AgentStat label="Open"     value={open.length}    accent={open.length > 0 ? "warn" : "good"} />
        <AgentStat label="Urgent"   value={urgent.length}  accent={urgent.length > 0 ? "danger" : "neutral"} />
        <AgentStat label="Accepted" value={accepted.length} accent="good" />
      </div>

      {/* Cards */}
      {recs.length > 0 ? (
        <div className="space-y-4">
          {recs.map(rec => (
            <div key={rec.id} className={`rounded-2xl border bg-[var(--color-bg-2)]/60 p-5 ${
              rec.priority === "urgent" ? "border-red-500/30" :
              rec.priority === "high"   ? "border-orange-500/20" :
              "border-[var(--color-line)]"
            }`}>
              <div className="flex items-start gap-4">
                <ConfidenceRing value={rec.confidence} />
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-4">
                    <p className="font-semibold text-sm leading-snug">{rec.title}</p>
                    <PriorityBadge priority={rec.priority} />
                  </div>
                  <p className="mt-1.5 text-xs text-[var(--color-ink-dim)] leading-relaxed">{rec.rationale}</p>

                  <div className="mt-3 space-y-1.5">
                    {rec.suggestedActions.map((action, i) => (
                      <div key={i} className="flex items-start gap-2">
                        <ChevronRight className="mt-0.5 h-3 w-3 shrink-0 text-[var(--color-blue)]" />
                        <span className="text-xs text-[var(--color-ink-dim)]">{action}</span>
                      </div>
                    ))}
                  </div>

                  <div className="mt-3 flex flex-wrap items-center gap-3">
                    <span className="text-[11px] text-[var(--color-ink-faint)]">
                      Impact: <span className={IMPACT_STYLES[rec.impactLabel] ?? "text-[var(--color-ink-dim)]"}>{rec.impactLabel}</span>
                    </span>
                    <span className="text-[11px] text-[var(--color-ink-faint)]">
                      Effort: <span className={EFFORT_STYLES[rec.effortLabel] ?? "text-[var(--color-ink-dim)]"}>{rec.effortLabel}</span>
                    </span>
                    <span className="text-[11px] text-[var(--color-ink-faint)]">by {rec.agentName}</span>
                    <span className="text-[11px] text-[var(--color-ink-faint)] ml-auto">{fmtDate(rec.createdAt)}</span>
                  </div>

                  {rec.status === "open" && (
                    <div className="mt-3 border-t border-[var(--color-line)]/40 pt-3">
                      <RecommendationActions recId={rec.id} />
                    </div>
                  )}
                  {rec.status !== "open" && (
                    <div className="mt-2 text-[11px] text-[var(--color-ink-faint)] capitalize">
                      Status: <span className={rec.status === "accepted" ? "text-emerald-400" : "text-red-400"}>{rec.status}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="rounded-2xl border border-dashed border-[var(--color-line)] bg-[var(--color-bg-2)]/40 flex flex-col items-center py-16 gap-4">
          <CheckCircle className="h-10 w-10 text-emerald-400 opacity-40" />
          <div className="text-center">
            <p className="font-semibold text-sm">No recommendations yet</p>
            <p className="mt-1 text-xs text-[var(--color-ink-dim)]">Agents generate recommendations after analyzing governance data.</p>
          </div>
        </div>
      )}
    </div>
  );
}
