import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./pdf-styles";
import type { Framework, Control, GapAnalysisRow } from "@/lib/db/schema";
import type { ReadinessScore } from "@/lib/db/schema";

type Props = {
  orgName: string;
  generatedBy: string;
  framework: Framework;
  readiness: ReadinessScore | null;
  controls: Control[];
  gaps: GapAnalysisRow[];
  summary: string | null; // AI-generated framework summary (cached)
};

function ControlStatusBadge({ status }: { status: string }) {
  const s =
    status === "implemented"    ? styles.badgeGreen  :
    status === "partial"        ? styles.badgeYellow :
    status === "not_applicable" ? styles.badgeGray   : styles.badgeRed;
  const label =
    status === "implemented"     ? "Implemented"    :
    status === "partial"         ? "Partial"        :
    status === "not_applicable"  ? "N/A"            : "Not Impl.";
  return <View style={[styles.badge, s]}><Text>{label}</Text></View>;
}

function PriorityBadge({ priority }: { priority: string }) {
  const s =
    priority === "critical" ? styles.badgeRed    :
    priority === "high"     ? styles.badgeRed    :
    priority === "medium"   ? styles.badgeYellow : styles.badgeGray;
  return <View style={[styles.badge, s]}><Text>{priority.toUpperCase()}</Text></View>;
}

function SeverityBadge({ severity }: { severity: string }) {
  const s =
    severity === "critical" ? styles.badgeRed    :
    severity === "high"     ? styles.badgeRed    :
    severity === "medium"   ? styles.badgeYellow : styles.badgeGray;
  return <View style={[styles.badge, s]}><Text>{severity.toUpperCase()}</Text></View>;
}

export function ComplianceFrameworkReport({
  orgName, generatedBy, framework, readiness, controls, gaps, summary,
}: Props) {
  const date = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const score = readiness?.overallScore ?? 0;
  const implemented  = controls.filter((c) => c.status === "implemented").length;
  const partial      = controls.filter((c) => c.status === "partial").length;
  const notImpl      = controls.filter((c) => c.status === "not_implemented").length;
  const criticalGaps = gaps.filter((g) => g.severity === "critical").length;
  const highGaps     = gaps.filter((g) => g.severity === "high").length;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.brandName}>LEKHA OS</Text>
            <Text style={styles.brandTag}>Trust. Governance. Compliance.</Text>
          </View>
          <View style={styles.reportTitle}>
            <Text style={styles.reportName}>Framework Readiness Report</Text>
            <Text style={styles.reportMeta}>{framework.name}{framework.version ? ` v${framework.version}` : ""}</Text>
            <Text style={styles.reportMeta}>{orgName} · {date}</Text>
            <Text style={styles.reportMeta}>Generated by {generatedBy}</Text>
          </View>
        </View>

        {/* Readiness summary cards */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Readiness Overview</Text>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{score}%</Text>
              <Text style={styles.summaryLabel}>Overall Readiness</Text>
            </View>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{readiness?.controlCoverage ?? 0}%</Text>
              <Text style={styles.summaryLabel}>Control Coverage</Text>
            </View>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{readiness?.evidenceCoverage ?? 0}%</Text>
              <Text style={styles.summaryLabel}>Evidence Coverage</Text>
            </View>
            <View style={[styles.summaryCard, { marginRight: 0 }]}>
              <Text style={styles.summaryValue}>{gaps.length}</Text>
              <Text style={styles.summaryLabel}>Open Gaps ({criticalGaps} critical)</Text>
            </View>
          </View>

          {/* Control status strip */}
          <View style={{ flexDirection: "row", marginBottom: 8 }}>
            {[
              { label: "Implemented",     value: implemented, color: "#065f46", bg: "#d1fae5" },
              { label: "Partial",         value: partial,     color: "#92400e", bg: "#fef3c7" },
              { label: "Not Implemented", value: notImpl,     color: "#991b1b", bg: "#fee2e2" },
            ].map((s, i) => (
              <View key={s.label} style={{
                flex: 1, padding: 8, backgroundColor: s.bg, borderRadius: 4,
                marginRight: i < 2 ? 6 : 0,
              }}>
                <Text style={{ fontSize: 14, fontFamily: "Helvetica-Bold", color: s.color }}>{s.value}</Text>
                <Text style={{ fontSize: 8, color: s.color, marginTop: 2 }}>{s.label}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* AI summary */}
        {summary && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>AI Summary</Text>
            <View style={{ padding: 10, backgroundColor: "#f1f3ff", borderRadius: 6, borderLeftWidth: 3, borderLeftColor: "#4f46e5", borderLeftStyle: "solid" }}>
              <Text style={{ fontSize: 9, lineHeight: 1.6, color: "#3730a3" }}>{summary}</Text>
            </View>
          </View>
        )}

        {/* Controls table */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Controls ({controls.length})</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableCellBold, { flex: 0.7 }]}>Ref</Text>
              <Text style={[styles.tableCellBold, { flex: 2.5 }]}>Control Name</Text>
              <Text style={styles.tableCellBold}>Category</Text>
              <Text style={styles.tableCellBold}>Priority</Text>
              <Text style={styles.tableCellBold}>Status</Text>
            </View>
            {controls.map((c) => (
              <View key={c.id} style={styles.tableRow}>
                <Text style={[styles.tableCell, { flex: 0.7, fontFamily: "Helvetica-Oblique", fontSize: 8 }]}>{c.controlRef}</Text>
                <Text style={[styles.tableCell, { flex: 2.5 }]}>{c.name}</Text>
                <Text style={styles.tableCell}>{c.category ?? "—"}</Text>
                <View style={styles.tableCell}><PriorityBadge priority={c.priority} /></View>
                <View style={styles.tableCell}><ControlStatusBadge status={c.status} /></View>
              </View>
            ))}
          </View>
        </View>

        {/* Gaps */}
        {gaps.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Open Gaps ({gaps.length})</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={[styles.tableCellBold, { flex: 0.8 }]}>Severity</Text>
                <Text style={[styles.tableCellBold, { flex: 1.2 }]}>Type</Text>
                <Text style={[styles.tableCellBold, { flex: 3 }]}>Description</Text>
              </View>
              {gaps.map((g) => (
                <View key={g.id} style={styles.tableRow}>
                  <View style={[styles.tableCell, { flex: 0.8 }]}><SeverityBadge severity={g.severity} /></View>
                  <Text style={[styles.tableCell, { flex: 1.2, fontSize: 8 }]}>{g.gapType.replace(/_/g, " ")}</Text>
                  <Text style={[styles.tableCell, { flex: 3, fontSize: 8 }]}>{g.description}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Lekha OS — Confidential · {orgName}</Text>
          <Text>{date}</Text>
        </View>
      </Page>
    </Document>
  );
}
