import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./pdf-styles";
import type { Framework, ReadinessScore, GapAnalysisRow, Policy } from "@/lib/db/schema";

type FrameworkRow = Framework & { readiness: ReadinessScore | null; openGapCount: number; controlCount: number };

type Props = {
  orgName: string;
  generatedBy: string;
  frameworks: FrameworkRow[];
  allGaps: GapAnalysisRow[];
  policies: Policy[];
  executiveSummary: string | null;
};

function ScoreBar({ value }: { value: number }) {
  const color = value >= 75 ? "#065f46" : value >= 50 ? "#1e40af" : value >= 25 ? "#92400e" : "#991b1b";
  const bg    = value >= 75 ? "#d1fae5" : value >= 50 ? "#dbeafe" : value >= 25 ? "#fef3c7" : "#fee2e2";
  return (
    <View style={{ flexDirection: "row", alignItems: "center" }}>
      <View style={{ flex: 1, height: 6, backgroundColor: "#f1f3ff", borderRadius: 3 }}>
        <View style={{ width: `${value}%`, height: 6, backgroundColor: color, borderRadius: 3 }} />
      </View>
      <Text style={{ marginLeft: 6, fontSize: 9, fontFamily: "Helvetica-Bold", color }}>{value}%</Text>
    </View>
  );
}

export function ComplianceExecutiveReport({
  orgName, generatedBy, frameworks, allGaps, policies, executiveSummary,
}: Props) {
  const date = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const scores = frameworks.map((f) => f.readiness?.overallScore ?? 0);
  const avgScore = scores.length ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : 0;
  const criticalGaps = allGaps.filter((g) => g.severity === "critical").length;
  const approvedPolicies = policies.filter((p) => p.status === "approved").length;
  const totalControls = frameworks.reduce((n, f) => n + f.controlCount, 0);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.brandName}>LEKHA OS</Text>
            <Text style={styles.brandTag}>Trust. Governance. Compliance.</Text>
          </View>
          <View style={styles.reportTitle}>
            <Text style={styles.reportName}>Executive Compliance Summary</Text>
            <Text style={styles.reportMeta}>{orgName} · {date}</Text>
            <Text style={styles.reportMeta}>Generated by {generatedBy}</Text>
          </View>
        </View>

        {/* Top-level metrics */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Compliance Posture</Text>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{avgScore}%</Text>
              <Text style={styles.summaryLabel}>Average Readiness</Text>
            </View>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{frameworks.length}</Text>
              <Text style={styles.summaryLabel}>Frameworks</Text>
            </View>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{totalControls}</Text>
              <Text style={styles.summaryLabel}>Total Controls</Text>
            </View>
            <View style={[styles.summaryCard, { marginRight: 0 }]}>
              <Text style={[styles.summaryValue, { color: criticalGaps > 0 ? "#991b1b" : "#065f46" }]}>
                {allGaps.length}
              </Text>
              <Text style={styles.summaryLabel}>Open Gaps ({criticalGaps} critical)</Text>
            </View>
          </View>
        </View>

        {/* AI narrative */}
        {executiveSummary && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>AI Executive Summary</Text>
            <View style={{ padding: 12, backgroundColor: "#f1f3ff", borderRadius: 6, borderLeftWidth: 3, borderLeftColor: "#4f46e5", borderLeftStyle: "solid" }}>
              <Text style={{ fontSize: 9.5, lineHeight: 1.7, color: "#1e1b4b" }}>{executiveSummary}</Text>
            </View>
          </View>
        )}

        {/* Framework table */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Framework Readiness</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableCellBold, { flex: 2 }]}>Framework</Text>
              <Text style={styles.tableCellBold}>Status</Text>
              <Text style={[styles.tableCellBold, { flex: 2 }]}>Readiness</Text>
              <Text style={styles.tableCellBold}>Controls</Text>
              <Text style={styles.tableCellBold}>Evidence %</Text>
              <Text style={styles.tableCellBold}>Gaps</Text>
            </View>
            {frameworks.map((fw) => (
              <View key={fw.id} style={styles.tableRow}>
                <View style={[styles.tableCell, { flex: 2 }]}>
                  <Text style={{ fontSize: 9, fontFamily: "Helvetica-Bold" }}>{fw.name}</Text>
                  {fw.version && <Text style={{ fontSize: 7, color: "#646a82" }}>v{fw.version}</Text>}
                </View>
                <Text style={styles.tableCell}>{fw.status.replace("_", " ")}</Text>
                <View style={[styles.tableCell, { flex: 2, justifyContent: "center" }]}>
                  <ScoreBar value={fw.readiness?.overallScore ?? 0} />
                </View>
                <Text style={styles.tableCell}>{fw.controlCount}</Text>
                <Text style={styles.tableCell}>{fw.readiness?.evidenceCoverage ?? 0}%</Text>
                <Text style={[styles.tableCell, {
                  color: fw.openGapCount > 0 ? "#991b1b" : "#065f46",
                  fontFamily: "Helvetica-Bold",
                }]}>
                  {fw.openGapCount}
                </Text>
              </View>
            ))}
          </View>
        </View>

        {/* Policy overview */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Policy Status</Text>
          <View style={styles.summaryGrid}>
            {[
              { label: "Total Policies",   value: policies.length },
              { label: "Approved",         value: approvedPolicies },
              { label: "In Review",        value: policies.filter((p) => p.status === "review").length },
              { label: "Expired/Overdue",  value: policies.filter((p) => p.status === "expired").length },
            ].map((s, i) => (
              <View key={s.label} style={[styles.summaryCard, { marginRight: i < 3 ? 8 : 0 }]}>
                <Text style={styles.summaryValue}>{s.value}</Text>
                <Text style={styles.summaryLabel}>{s.label}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Gap severity breakdown */}
        {allGaps.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Gap Breakdown</Text>
            <View style={{ flexDirection: "row" }}>
              {[
                { label: "Critical", value: criticalGaps, color: "#991b1b", bg: "#fee2e2" },
                { label: "High",     value: allGaps.filter((g) => g.severity === "high").length,   color: "#991b1b", bg: "#fee2e2" },
                { label: "Medium",   value: allGaps.filter((g) => g.severity === "medium").length, color: "#92400e", bg: "#fef3c7" },
                { label: "Low",      value: allGaps.filter((g) => g.severity === "low").length,    color: "#1e40af", bg: "#dbeafe" },
              ].map((s, i) => (
                <View key={s.label} style={{
                  flex: 1, padding: 8, backgroundColor: s.bg, borderRadius: 4,
                  marginRight: i < 3 ? 6 : 0,
                }}>
                  <Text style={{ fontSize: 16, fontFamily: "Helvetica-Bold", color: s.color }}>{s.value}</Text>
                  <Text style={{ fontSize: 8, color: s.color, marginTop: 2 }}>{s.label}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Lekha OS — Executive Compliance Summary · {orgName} · Confidential</Text>
          <Text>{date}</Text>
        </View>
      </Page>
    </Document>
  );
}
