import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./pdf-styles";

export type ExpiryDocRow = {
  vendorName: string;
  documentType: string;
  expiresOn: string | null;
  status: string;
  daysLeft: number | null;
};

type Props = { orgName: string; generatedBy: string; rows: ExpiryDocRow[] };

export function ExpiryReport({ orgName, generatedBy, rows }: Props) {
  const date = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

  const urgent = rows.filter((r) => r.status === "expired" || (r.daysLeft !== null && r.daysLeft <= 15));
  const soon = rows.filter((r) => r.daysLeft !== null && r.daysLeft > 15 && r.daysLeft <= 30);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View><Text style={styles.brandName}>LEKHA OS</Text><Text style={styles.brandTag}>Trust. Governance. Compliance.</Text></View>
          <View style={styles.reportTitle}>
            <Text style={styles.reportName}>Expiry Report</Text>
            <Text style={styles.reportMeta}>{orgName} · {date}</Text>
            <Text style={styles.reportMeta}>Generated by {generatedBy}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryCard}><Text style={styles.summaryValue}>{rows.filter((r) => r.status === "expired").length}</Text><Text style={styles.summaryLabel}>Expired</Text></View>
            <View style={styles.summaryCard}><Text style={styles.summaryValue}>{urgent.length}</Text><Text style={styles.summaryLabel}>Urgent (≤15 days)</Text></View>
            <View style={styles.summaryCard}><Text style={styles.summaryValue}>{soon.length}</Text><Text style={styles.summaryLabel}>Expiring 16–30 days</Text></View>
          </View>
        </View>

        {rows.length === 0 ? (
          <Text style={{ color: "#646a82", textAlign: "center", marginTop: 40 }}>No expiring or expired documents.</Text>
        ) : (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Documents ({rows.length})</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={[styles.tableCellBold, { flex: 2 }]}>Vendor</Text>
                <Text style={[styles.tableCellBold, { flex: 2 }]}>Document</Text>
                <Text style={styles.tableCellBold}>Status</Text>
                <Text style={styles.tableCellBold}>Expires</Text>
                <Text style={styles.tableCellBold}>Days Left</Text>
              </View>
              {rows.map((r, i) => {
                const badgeStyle = r.status === "expired" ? styles.badgeRed : styles.badgeYellow;
                return (
                  <View key={i} style={styles.tableRow}>
                    <Text style={[styles.tableCell, { flex: 2 }]}>{r.vendorName}</Text>
                    <Text style={[styles.tableCell, { flex: 2 }]}>{r.documentType}</Text>
                    <View style={styles.tableCell}><View style={[styles.badge, badgeStyle]}><Text>{r.status}</Text></View></View>
                    <Text style={styles.tableCell}>{r.expiresOn ?? "—"}</Text>
                    <Text style={[styles.tableCell, { color: r.status === "expired" ? "#991b1b" : "#92400e" }]}>{r.daysLeft !== null ? (r.daysLeft < 0 ? `${Math.abs(r.daysLeft)}d ago` : `${r.daysLeft}d`) : "—"}</Text>
                  </View>
                );
              })}
            </View>
          </View>
        )}

        <View style={styles.footer}><Text>Lekha OS — Confidential</Text><Text>{date}</Text></View>
      </Page>
    </Document>
  );
}
