import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./pdf-styles";
import { RISK_CATEGORY_LABELS, scoreToLevel } from "@/backend/src/modules/risk-lens/risk-scoring";

export type ExecTopRisk = { id: string; title: string; category: string; inherentScore: number };

type Props = {
  orgName: string;
  generatedBy: string;
  metrics: {
    total: number;
    open: number;
    mitigating: number;
    accepted: number;
    critical: number;
    overdueReviews: number;
    topRisks: ExecTopRisk[];
  };
  executiveSummary: string | null;
};

export function RiskExecutiveReport({ orgName, generatedBy, metrics, executiveSummary }: Props) {
  const date = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const paragraphs = (executiveSummary ?? "").split(/\n+/).map((s) => s.trim()).filter(Boolean);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.brandName}>AUDT</Text>
            <Text style={styles.brandTag}>Governance Built on Proof.</Text>
          </View>
          <View style={styles.reportTitle}>
            <Text style={styles.reportName}>Executive Risk Report</Text>
            <Text style={styles.reportMeta}>{orgName} · {date}</Text>
            <Text style={styles.reportMeta}>Generated by {generatedBy}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Risk Posture</Text>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{metrics.total}</Text>
              <Text style={styles.summaryLabel}>Total Risks</Text>
            </View>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{metrics.critical}</Text>
              <Text style={styles.summaryLabel}>Critical</Text>
            </View>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{metrics.mitigating}</Text>
              <Text style={styles.summaryLabel}>Mitigating</Text>
            </View>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{metrics.overdueReviews}</Text>
              <Text style={styles.summaryLabel}>Overdue Reviews</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Top Risks by Score</Text>
          {metrics.topRisks.length === 0 ? (
            <Text style={{ fontSize: 9, color: "#64748b" }}>No active risks.</Text>
          ) : (
            metrics.topRisks.map((r, i) => (
              <View key={r.id} style={{ flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#e2e8f0", paddingVertical: 3 }}>
                <Text style={{ width: 18, fontSize: 9, fontFamily: "Helvetica-Bold" }}>{i + 1}.</Text>
                <Text style={{ flex: 1, fontSize: 9, paddingRight: 4 }}>{r.title}</Text>
                <Text style={{ width: 90, fontSize: 9 }}>{RISK_CATEGORY_LABELS[r.category] ?? r.category}</Text>
                <Text style={{ width: 70, fontSize: 9 }}>{r.inherentScore} · {scoreToLevel(r.inherentScore)}</Text>
              </View>
            ))
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>AI Executive Summary</Text>
          {paragraphs.length === 0 ? (
            <Text style={{ fontSize: 9, color: "#64748b" }}>
              No executive summary generated yet. Generate one from the AI Risk Officer™ tab, then re-export.
            </Text>
          ) : (
            paragraphs.map((p, i) => (
              <Text key={i} style={{ fontSize: 9, marginBottom: 6, lineHeight: 1.4 }}>{p}</Text>
            ))
          )}
        </View>
      </Page>
    </Document>
  );
}
