import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./pdf-styles";
import { RISK_CATEGORY_LABELS, RISK_STATUS_LABELS, scoreToLevel } from "@/backend/src/modules/risk-lens/risk-scoring";

export type RiskRow = {
  id: string;
  title: string;
  category: string;
  status: string;
  ownerName: string | null;
  impact: number;
  likelihood: number;
  inherentScore: number;
  treatmentStrategy: string | null;
  targetDate: string | null;
};

type Props = {
  orgName: string;
  generatedBy: string;
  risks: RiskRow[];
};

const cell = (flex: number): { flex: number; paddingRight: number } => ({ flex, paddingRight: 4 });

export function RiskRegisterReport({ orgName, generatedBy, risks }: Props) {
  const date = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const active = risks.filter((r) => !["closed", "archived"].includes(r.status));
  const critical = active.filter((r) => r.inherentScore >= 16).length;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.brandName}>AUDT</Text>
            <Text style={styles.brandTag}>Governance Built on Proof.</Text>
          </View>
          <View style={styles.reportTitle}>
            <Text style={styles.reportName}>Risk Register</Text>
            <Text style={styles.reportMeta}>{orgName} · {date}</Text>
            <Text style={styles.reportMeta}>Generated by {generatedBy}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Risk Posture</Text>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{risks.length}</Text>
              <Text style={styles.summaryLabel}>Total Risks</Text>
            </View>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{active.length}</Text>
              <Text style={styles.summaryLabel}>Active</Text>
            </View>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryValue}>{critical}</Text>
              <Text style={styles.summaryLabel}>Critical (≥16)</Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>All Risks</Text>
          {/* Table header */}
          <View style={{ flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#1e293b", paddingBottom: 4, marginBottom: 4 }}>
            <Text style={{ ...cell(3), fontFamily: "Helvetica-Bold", fontSize: 9 }}>Title</Text>
            <Text style={{ ...cell(2), fontFamily: "Helvetica-Bold", fontSize: 9 }}>Category</Text>
            <Text style={{ ...cell(2), fontFamily: "Helvetica-Bold", fontSize: 9 }}>Status</Text>
            <Text style={{ ...cell(1), fontFamily: "Helvetica-Bold", fontSize: 9 }}>Score</Text>
            <Text style={{ ...cell(2), fontFamily: "Helvetica-Bold", fontSize: 9 }}>Owner</Text>
          </View>
          {risks.map((r) => (
            <View key={r.id} style={{ flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#e2e8f0", paddingVertical: 3 }}>
              <Text style={{ ...cell(3), fontSize: 9 }}>{r.title}</Text>
              <Text style={{ ...cell(2), fontSize: 9 }}>{RISK_CATEGORY_LABELS[r.category] ?? r.category}</Text>
              <Text style={{ ...cell(2), fontSize: 9 }}>{RISK_STATUS_LABELS[r.status] ?? r.status}</Text>
              <Text style={{ ...cell(1), fontSize: 9 }}>{r.inherentScore} · {scoreToLevel(r.inherentScore)}</Text>
              <Text style={{ ...cell(2), fontSize: 9 }}>{r.ownerName ?? "Unassigned"}</Text>
            </View>
          ))}
          {risks.length === 0 && <Text style={{ fontSize: 9, color: "#64748b" }}>No risks recorded.</Text>}
        </View>
      </Page>
    </Document>
  );
}
