import React from "react";
import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles } from "./pdf-styles";
import type { VendorRow } from "@/backend/src/modules/vendor-hub/vendor-service";
import type { VendorMetrics } from "@/backend/src/modules/vendor-hub/vendor-service";

function StatusBadge({ status }: { status: string }) {
  const style = status === "active" ? styles.badgeGreen : status === "inactive" ? styles.badgeGray : styles.badgeYellow;
  return <View style={[styles.badge, style]}><Text>{status}</Text></View>;
}

function RiskBadge({ risk }: { risk: string }) {
  const style = risk === "low" ? styles.badgeGreen : risk === "medium" ? styles.badgeYellow : styles.badgeRed;
  return <View style={[styles.badge, style]}><Text>{risk}</Text></View>;
}

type Props = {
  orgName: string;
  generatedBy: string;
  vendors: VendorRow[];
  metrics: VendorMetrics;
};

export function VendorComplianceReport({ orgName, generatedBy, vendors, metrics }: Props) {
  const date = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.brandName}>LEKHA OS</Text>
            <Text style={styles.brandTag}>Trust. Governance. Compliance.</Text>
          </View>
          <View style={styles.reportTitle}>
            <Text style={styles.reportName}>Vendor Compliance Report</Text>
            <Text style={styles.reportMeta}>{orgName} · {date}</Text>
            <Text style={styles.reportMeta}>Generated by {generatedBy}</Text>
          </View>
        </View>

        {/* Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Executive Summary</Text>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryCard}><Text style={styles.summaryValue}>{metrics.totalVendors}</Text><Text style={styles.summaryLabel}>Total Vendors</Text></View>
            <View style={styles.summaryCard}><Text style={styles.summaryValue}>{metrics.complianceScore}</Text><Text style={styles.summaryLabel}>Avg Compliance Score</Text></View>
            <View style={styles.summaryCard}><Text style={styles.summaryValue}>{metrics.expiringSoon}</Text><Text style={styles.summaryLabel}>Expiring in 30 Days</Text></View>
            <View style={styles.summaryCard}><Text style={styles.summaryValue}>{metrics.highRisk}</Text><Text style={styles.summaryLabel}>High / Critical Risk</Text></View>
          </View>
        </View>

        {/* Vendor table */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Vendor Registry ({vendors.length})</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={[styles.tableCellBold, { flex: 2 }]}>Vendor</Text>
              <Text style={styles.tableCellBold}>Category</Text>
              <Text style={styles.tableCellBold}>Status</Text>
              <Text style={styles.tableCellBold}>Risk</Text>
              <Text style={styles.tableCellBold}>Docs</Text>
              <Text style={[styles.tableCellBold, { textAlign: "right" }]}>Score</Text>
            </View>
            {vendors.map((v) => (
              <View key={v.id} style={styles.tableRow}>
                <Text style={[styles.tableCell, { flex: 2 }]}>{v.name}</Text>
                <Text style={styles.tableCell}>{v.category ?? "—"}</Text>
                <View style={styles.tableCell}><StatusBadge status={v.status} /></View>
                <View style={styles.tableCell}><RiskBadge risk={v.risk} /></View>
                <Text style={styles.tableCell}>{v.docs}</Text>
                <Text style={[styles.tableCell, { textAlign: "right", fontFamily: "Helvetica-Bold" }]}>{v.score}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Lekha OS — Confidential</Text>
          <Text>{date}</Text>
        </View>
      </Page>
    </Document>
  );
}
